name: Enviroment
on:
  push:
  workflow_dispatch:
env:
  NODE_ENV: production
  GH_SECRET: ${{ secrets.DEPLOY_SECRET}} # SECRET FROM gh

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production-deploy # Переопределяем глобальную переменную на свою
    steps:
      - name: Print Env Build
        run: |
          echo "${{ env.NODE_ENV }}"
          echo "${{ env.GH_SECRET }}"
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Print Env deploy
        run: |
          echo "${{ env.NODE_ENV }}"
          echo "${{ env.GH_SECRET }}"
